export const EXPENSE_CATEGORIES = [
  "food",
  "house_rent",
  "utility",
  "transport",
  "entertainment",
  "healthcare",
  "education",
  "shopping",
  "travel",
  "insurance",
  "taxes",
  "savings",
  "investment",
  "donation",
  "personal_care",
  "subscriptions",
  "family",
  "pets",
  "gifts",
  "other",
] as const;

export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number];

export const SUBCATEGORIES_BY_CATEGORY: Record<ExpenseCategory, string[]> = {
  food: ["Restaurant", "Groceries", "Snacks", "Coffee", "Delivery"],
  house_rent: ["Monthly Rent", "Service Charge", "Repairs", "Security"],
  utility: ["Electricity", "Water", "Internet", "Cooking Gas", "Waste Disposal"],
  transport: ["Fuel", "Public Transit", "Ride Hailing", "Car Maintenance", "Parking"],
  entertainment: ["Cinema", "Concerts", "Gaming", "Streaming", "Nightlife"],
  healthcare: ["Medications", "Consultation", "Dental", "Lab Tests", "Glasses"],
  education: ["Tuition", "Courses & Books", "Certifications", "Stationery"],
  shopping: ["Clothing", "Footwear", "Electronics", "Home Appliances"],
  travel: ["Flights", "Hotel & Lodging", "Visa & Logistics", "Car Rental"],
  insurance: ["Health Insurance", "Auto Insurance", "Life Insurance", "Property"],
  taxes: ["Income Tax", "Property Tax", "VAT / Levies"],
  savings: ["Emergency Fund", "Target Savings", "Sinking Fund"],
  investment: ["Stocks", "Real Estate", "Mutual Funds", "Bonds"],
  donation: ["Charity", "Religious Tithes", "Community Support"],
  personal_care: ["Haircut & Salon", "Skincare", "Gym & Fitness", "Spa"],
  subscriptions: ["Cloud Storage", "Software Licenses", "Media", "Newsletters"],
  family: ["Childcare", "School Supplies", "Parent Allowance", "Remittances"],
  pets: ["Pet Food", "Veterinary", "Grooming", "Accessories"],
  gifts: ["Birthdays", "Weddings", "Holidays", "Celebrations"],
  other: ["Uncategorized", "Emergency Out-of-pocket", "Miscellaneous"],
};